Backend6/Models/CarDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend6.Models
{
    public class CarDetail
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public Guid CarPartId { get; set; }
        public CarPart CarPart { get; set; }

        public Guid BasketId { get; set; }

        public Basket Basket { get; set; }

        public ICollection<Attachment> Attachments { get; set; }

        [Required]
        public String DetailPath { get; set; }

        [Required]
        public String Name { get; set; }

        public String Description { get; set; }

        [Required]
        public Int32 Cost { get; set; }

    }
}

Backend6/Controllers/CarDetailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Models.ViewModels;
//using Backend6.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;

namespace Backend6.Controllers
{
    public class CarDetailsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        //private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarDetailsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/*, IUserPermissionsService userPermissions*/, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            this.userManager = userManager;
            //this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CarDetails
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CarDetails.Include(c => c.Basket).Include(c => c.CarPart);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CarDetails/Details/5
        public async Task<IActionResult> Details(Guid? carDetailId)
        {
            if (carDetailId == null)
            {
                return NotFound();
            }

            var carDetail = await _context.CarDetails
                .Include(c => c.Basket)
                .Include(c => c.CarPart)
                .SingleOrDefaultAsync(m => m.Id == carDetailId);
            if (carDetail == null)
            {
                return NotFound();
            }
            this.ViewBag.CarDetailId = carDetailId;
            return View(carDetail);
        }
        [Authorize]
        // GET: CarDetails/Create
        public async Task<IActionResult> Create(Guid? carPartId)
        {
            if (carPartId == null)
            {
                return this.NotFound();
            }
            var carPart = await this._context.CarParts
                .SingleOrDefaultAsync(m => m.Id == carPartId);
            if (carPart == null)
            {
                return this.NotFound();
            }
            var carParts = await this._context.CarParts
                .OrderBy(x => x.Name).ToListAsync();
            var baskets = await this._context.Baskets
               .OrderBy(x => x.FullPrice).ToListAsync();
            ViewData["BasketId"] = new SelectList(baskets, "Id", "CreatorId");
            ViewData["CarPartId"] = new SelectList(carParts, "Id", "Name");
            this.ViewBag.CarParts = carPart;
            return View(new CarDetailEditModel());
        }

        // POST: CarDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? carPartId, CarDetailEditModel model)
        {
            if (carPartId == null)
            {
                this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.DetailPath.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);
            if (!CarDetailsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.DetailPath), "This file type is prohibited");
            }

            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var carPart = await this._context.CarParts                
                .SingleOrDefaultAsync(m => m.Id == carPartId);
            var baskets = await this._context.Baskets
                .Include(p => p.CarDetails)
                .Include(u => u.Creator)
                .SingleOrDefaultAsync(m => m.Id == carPartId);
            
            if (carPart == null)
            {
                this.NotFound();
            }

            if (ModelState.IsValid)
            {

                var carDetail = new CarDetail
                {
                    CarPartId = carPart.Id,
                    //BasketId = baskets.Creator.Id,
                    Name = model.Name,
                    Description = model.Description,
                    Cost = model.Cost
                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments/parts", carDetail.Id.ToString("N") + fileExt);
                carDetail.DetailPath = $"/attachments/parts/{carDetail.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.DetailPath.CopyToAsync(fileStream);
                }

                carDetail.Id = Guid.NewGuid();
                _context.Add(carDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "CarParts", new { carPartId = carPart.Id });
            }
            ViewData["BasketId"] = new SelectList(_context.Baskets, "Id", "CreatorId");
            ViewData["CarPartId"] = new SelectList(_context.CarParts, "Id", "Name");
            this.ViewBag.CarParts = carPart;
            return View(model);
        }

        // GET: CarDetails/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carDetail = await _context.CarDetails.SingleOrDefaultAsync(m => m.Id == id);
            if (carDetail == null)
            {
                return NotFound();
            }
            ViewData["BasketId"] = new SelectList(_context.Baskets, "Id", "CreatorId", carDetail.BasketId);
            ViewData["CarPartId"] = new SelectList(_context.CarParts, "Id", "Name", carDetail.CarPartId);
            return View(carDetail);
        }

        // POST: CarDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,CarPartId,BasketId,DetailPath,Name,Description,Cost")] CarDetail carDetail)
        {
            if (id != carDetail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarDetailExists(carDetail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BasketId"] = new SelectList(_context.Baskets, "Id", "CreatorId", carDetail.BasketId);
            ViewData["CarPartId"] = new SelectList(_context.CarParts, "Id", "Name", carDetail.CarPartId);
            return View(carDetail);
        }

        // GET: CarDetails/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carDetail = await _context.CarDetails
                .Include(c => c.Basket)
                .Include(c => c.CarPart)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carDetail == null)
            {
                return NotFound();
            }

            return View(carDetail);
        }

        // POST: CarDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var carDetail = await _context.CarDetails.SingleOrDefaultAsync(m => m.Id == id);
            _context.CarDetails.Remove(carDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarDetailExists(Guid id)
        {
            return _context.CarDetails.Any(e => e.Id == id);
        }
    }
}

Backend6/Views/CarDetails/Create.cshtml
@model Backend6.Models.ViewModels.CarDetailEditModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>CarDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="CarDetails" asp-route-carPartId="@ViewBag.CarParts.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="CarPartId" class="control-label"></label>
                <select asp-for="CarPartId" class ="form-control" asp-items="ViewBag.CarPartId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BasketId" class="control-label"></label>
                <select asp-for="BasketId" class ="form-control" asp-items="ViewBag.BasketId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="DetailPath" class="control-label"></label>
                <input type="file" asp-for="DetailPath" class="form-control" />
                <span asp-validation-for="DetailPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarDetails/Delete.cshtml
@model Backend6.Models.CarDetail

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DetailPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DetailPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Basket)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Basket.CreatorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarPart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarPart.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Backend6/Views/CarDetails/Details.cshtml
@model Backend6.Models.CarDetail

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>CarDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DetailPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DetailPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Basket)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Basket.CreatorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarPart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarPart.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Backend6/Views/CarDetails/Edit.cshtml
@model Backend6.Models.CarDetail

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>CarDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CarPartId" class="control-label"></label>
                <select asp-for="CarPartId" class="form-control" asp-items="ViewBag.CarPartId"></select>
                <span asp-validation-for="CarPartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasketId" class="control-label"></label>
                <select asp-for="BasketId" class="form-control" asp-items="ViewBag.BasketId"></select>
                <span asp-validation-for="BasketId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DetailPath" class="control-label"></label>
                <input asp-for="DetailPath" class="form-control" />
                <span asp-validation-for="DetailPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarDetails/Index.cshtml
@model IEnumerable<Backend6.Models.CarDetail>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DetailPath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cost)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Basket)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarPart)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DetailPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Basket.CreatorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarPart.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>