Backend6/Models/CarPart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend6.Models
{
    public class CarPart
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public Guid CarGradeId { get; set; }
        public CarGrade CarGrade { get; set; }

        public ICollection<CarDetail> CarDetails { get; set; }

        [Required]
        public String PartPath { get; set; }

        [Required]
        public String Name { get; set; }

        public String Description { get; set; }
    }
}

Backend6/Controllers/CarModelsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Models.ViewModels;
//using Backend6.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;

namespace Backend6.Controllers
{
    public class CarModelsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        //private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarModelsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/*, IUserPermissionsService userPermissions*/, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            this.userManager = userManager;
            //this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CarModels
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CarModels
                .Include(c => c.CarBrand);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: CarModels/Details/5
        public async Task<IActionResult> Details(Guid? carModelId)
        {
            if (carModelId == null)
            {
                return this.NotFound();
            }

            var carModel = await this._context.CarModels
                .Include(g => g.CarGrades)
                .SingleOrDefaultAsync(m => m.Id == carModelId);
            if (carModel == null)
            {
                return this.NotFound();
            }

            this.ViewBag.CarModelId = carModelId;
            return this.View(carModel);
        }
        [Authorize]
        // GET: CarModels/Create
        public async Task<IActionResult> Create(Guid? carBrandId)
        {
            if (carBrandId == null)
            {
                return this.NotFound();
            }

            var carBrand = await this._context.CarBrands
                .SingleOrDefaultAsync(m => m.Id == carBrandId);

            if (carBrand == null)
            {
                return this.NotFound();
            }

            var carBrands = await this._context.CarBrands
                .OrderBy(x => x.Name).ToListAsync();

            this.ViewData["CarBrandId"] = new SelectList(carBrands, "Id", "Name");
            this.ViewBag.CarBrands = carBrand;
            return this.View(new CarModelEditModel());
        }        
        

        // POST: CarModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? carBrandId, CarModelEditModel model)
        {
            if (carBrandId == null)
            {                
                this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.ModelPath.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            if (!CarModelsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.ModelPath), "This file type is prohibited");
            }

            var carBrand = await this._context.CarBrands
                .SingleOrDefaultAsync(m => m.Id == carBrandId);

            if (carBrand == null)
            {
                this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                var carModel = new CarModel
                {
                    CarBrandId = carBrand.Id,
                    Name = model.Name,
                    Description = model.Description
                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments/models", carModel.Id.ToString("N") + fileExt);
                carModel.ModelPath = $"/attachments/models/{carModel.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.ModelPath.CopyToAsync(fileStream);
                }


                carModel.Id = Guid.NewGuid();
                this._context.Add(carModel);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarBrands", new { carId = carBrand.Id });
            }
            this.ViewData["CarBrandId"] = new SelectList(this._context.CarBrands, "Id", "Name");
            this.ViewBag.CarBrands = carBrand;
            return this.View(model);
        }

        // GET: CarModels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carModel = await this._context.CarModels
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carModel == null)
            {
                return this.NotFound();
            }
            this.ViewData["CarBrandId"] = new SelectList(this._context.CarBrands, "Id", "Name", carModel.CarBrandId);
            return this.View(carModel);
        }

        // POST: CarModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, CarModelEditModel model)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carModel = await this._context.CarModels
                .SingleOrDefaultAsync(m => m.Id == id);

            if (carModel == null)
            {
                return this.NotFound();
            }
            if (this.ModelState.IsValid)
            {
                carModel.Name = model.Name;
                carModel.Description = model.Description;

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarBrands", new { carId = carModel.CarBrandId });
            }
            this.ViewData["CarBrandId"] = new SelectList(this._context.CarBrands, "Id", "Name", carModel.CarBrandId);
            return this.View(model);
        }

        // GET: CarModels/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carModel = await this._context.CarModels                
                .Include(c => c.CarBrand)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carModel == null)
            {
                return this.NotFound();
            }
            this.ViewBag.CarBrands = carModel;
            return this.View(carModel);
        }

        // POST: CarModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid carBrandId)
        {
            if (carBrandId == null)
            {
                return this.NotFound();
            }

            var carModel = await this._context.CarModels
                .Include(c => c.CarBrand)
                .SingleOrDefaultAsync(m => m.Id == carBrandId);
            if (carModel == null)
            {
                return this.NotFound();
            }
            this._context.CarModels.Remove(carModel);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction("Details", "CarBrands", new { carId = carModel.CarBrand.Id });
        }

        private bool CarModelExists(Guid id)
        {
            return this._context.CarModels.Any(e => e.Id == id);
        }
    }
}

Backend6/Controllers/CarPartsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Models.ViewModels;
//using Backend6.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;


namespace Backend6.Controllers
{
    public class CarPartsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        //private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarPartsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/*, IUserPermissionsService userPermissions*/, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            this.userManager = userManager;
            //this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CarParts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this._context.CarParts
                .Include(c => c.CarGrade);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: CarParts/Details/5
        public async Task<IActionResult> Details(Guid? carPartId)
        {
            if (carPartId == null)
            {
                return this.NotFound();
            }

            var carPart = await this._context.CarParts
                .Include(c => c.CarGrade)
                .Include(b => b.CarDetails)
                .SingleOrDefaultAsync(m => m.Id == carPartId);
            if (carPart == null)
            {
                return this.NotFound();
            }
            this.ViewBag.CarPartId = carPartId;
            return this.View(carPart);
        }
        [Authorize]
        // GET: CarParts/Create
        public async Task<IActionResult> Create(Guid? carGradeId)
        {
            if (carGradeId == null)
            {
                return this.NotFound();
            }
            var carGrade = await this._context.CarGrades
                .SingleOrDefaultAsync(m => m.Id == carGradeId);
            if (carGrade == null)
            {
                return this.NotFound();
            }

            var carGrades = await this._context.CarGrades
                .OrderBy(x => x.Name).ToListAsync();
            this.ViewData["CarGradeId"] = new SelectList(carGrades, "Id", "Name");
            this.ViewBag.CarGrades = carGrade;
            return this.View(new CarPartEditModel());
        }

        // POST: CarParts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? carGradeId, CarPartEditModel model)
        {
            if (carGradeId == null)
            {
                this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.PartPath.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            if (!CarPartsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.PartPath), "This file type is prohibited");
            }

            var carGrade = await this._context.CarGrades
                .SingleOrDefaultAsync(m => m.Id == carGradeId);
            if (carGrade == null)
            {
                this.NotFound();
            }


            if (this.ModelState.IsValid)
            {
                var carPart = new CarPart
                {
                    CarGradeId = carGrade.Id,
                    Name = model.Name,
                    Description = model.Description

                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments/parts", carPart.Id.ToString("N") + fileExt);
                carPart.PartPath = $"/attachments/parts/{carPart.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.PartPath.CopyToAsync(fileStream);
                }

                carPart.Id = Guid.NewGuid();
                this._context.Add(carPart);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarGrades", new { carGradeId = carGrade.Id });
            }
            this.ViewData["CarGradeId"] = new SelectList(this._context.CarGrades, "Id", "GradePath");
            this.ViewBag.CarGrades = carGrade;
            return this.View(model);
        }

        // GET: CarParts/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carPart = await this._context.CarParts
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carPart == null)
            {
                return this.NotFound();
            }
            this.ViewData["CarGradeId"] = new SelectList(this._context.CarGrades, "Id", "GradePath", carPart.CarGradeId);
            return this.View(carPart);
        }

        // POST: CarParts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, CarPartEditModel model)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carPart = await this._context.CarParts
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carPart == null)
            {
                return this.NotFound();
            }
            if (this.ModelState.IsValid)
            {
                carPart.Name = model.Name;
                carPart.Description = model.Description;

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarGrades", new { carGradeId = carPart.CarGradeId });
            }
            this.ViewData["CarGradeId"] = new SelectList(this._context.CarGrades, "Id", "GradePath", carPart.CarGradeId);
            return this.View(model);
        }

        // GET: CarParts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carPart = await this._context.CarParts
                .Include(c => c.CarGrade)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carPart == null)
            {
                return this.NotFound();
            }

            this.ViewBag.CarGrades = carPart; 
            return this.View(carPart);
        }

        // POST: CarParts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid carGradeId)
        {
            if (carGradeId == null)
            {
                return this.NotFound();
            }
            var carPart = await this._context.CarParts
                .Include(c=> c.CarGrade)
                .SingleOrDefaultAsync(m => m.Id == carGradeId);
            if (carPart == null)
            {
                return this.NotFound();
            }
            this._context.CarParts.Remove(carPart);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction("Details", "CarGrades", new { carGradeId = carPart.CarGrade.Id });
        }

        private bool CarPartExists(Guid id)
        {
            return this._context.CarParts.Any(e => e.Id == id);
        }
    }
}

Backend6/Views/CarParts/Create.cshtml
@model Backend6.Models.ViewModels.CarPartEditModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>CarPart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="CarParts" asp-route-carGradeId="@ViewBag.CarGrades.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="CarGradeId" class="control-label"></label>
                <select asp-for="CarGradeId" class ="form-control" asp-items="ViewBag.CarGradeId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="PartPath" class="control-label"></label>
                <input type="file" asp-for="PartPath" class="form-control" />
                <span asp-validation-for="PartPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarParts/Delete.cshtml
@model Backend6.Models.CarPart

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarPart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PartPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarGrade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarGrade.GradePath)
        </dd>
    </dl>
    
    <form asp-action="Delete"  asp-route-carGradeId="@Model.Id">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Backend6/Views/CarParts/Details.cshtml
@model Backend6.Models.CarPart

@{
    ViewData["Title"] = "Выберите нужную деталь";
}

<h2>@ViewBag.Title</h2>
<h1>@Model.Name<small> @Model.Description</small></h1>
<p>
    <a asp-controller="CarModels" asp-action="Details" asp-route-backId="" class="btn btn-default">Back</a>
</p>

<div class="row">
    @if (User.IsInRole(ApplicationRoles.Administrators))
    {
        <div class="col-xs-3 col-md-2">
            <p>Добавить деталь</p>
            <a asp-action="Create" asp-controller="CarDetails" asp-route-carPartId="@ViewBag.CarPartId" class="thumbnail new-image">
                <div>
                    + Upload
                </div>
            </a>
        </div>
    }
    @foreach (var item in Model.CarDetails)
    {
        <div class="col-xs-3 col-md-2">
            <p>@item.Name</p>
            <a asp-action="Details" asp-controller="CarParts" asp-route-carPartId="@item.Id" class="thumbnail image">
                <img src="@item.DetailPath" alt="Image" />
            </a>
            @if (User.IsInRole(ApplicationRoles.Administrators))
            {
                <a asp-action="Edit" asp-controller="CarParts" asp-route-id="@item.Id">Edit</a> <text>|</text>
                <a asp-action="Delete" asp-controller="CarParts" asp-route-id="@item.Id">Delete</a>
            }
            <p>@Model.Name</p>
        </div>
    }
</div>

Backend6/Views/CarParts/Edit.cshtml
@model Backend6.Models.CarPart
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>CarPart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CarGradeId" class="control-label"></label>
                <select asp-for="CarGradeId" class="form-control" asp-items="ViewBag.CarGradeId"></select>
                <span asp-validation-for="CarGradeId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="PartPath" class="control-label"></label>
                <input asp-for="PartPath" class="form-control" />
                <span asp-validation-for="PartPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarParts/Index.cshtml
@model IEnumerable<Backend6.Models.CarPart>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PartPath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.CarGrade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PartPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarGrade.GradePath)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>