Backend6/Models/CarModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend6.Models
{
    public class CarModel
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public Guid CarBrandId { get; set; }
        public CarBrand CarBrand { get; set; }

        public ICollection<CarGrade> CarGrades { get; set; }

        [Required]
        public String ModelPath { get; set; }

        [Required]
        public String Name { get; set; }

        public String Description { get; set; }
    }
}

Backend6/Controllers/CarBrandsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Models.ViewModels;
//using Backend6.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;


namespace Backend6.Controllers
{
    public class CarBrandsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        //private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarBrandsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/*, IUserPermissionsService userPermissions*/, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            this.userManager = userManager;
            //this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CarBrands
        public async Task<IActionResult> Index()
        {
            return this.View(await this._context.CarBrands.ToListAsync());
        }

        // GET: CarBrands/Details/5
        public async Task<IActionResult> Details(Guid? carId)
        {
            if (carId == null)
            {
                return this.NotFound();
            }

            var carBrand = await this._context.CarBrands
                .Include(f => f.CarModels)
                .SingleOrDefaultAsync(m => m.Id == carId);
            if (carBrand == null)
            {
                return this.NotFound();
            }
            this.ViewBag.CarBrandId = carId;
            return this.View(carBrand);
        }
        [Authorize]
        // GET: CarBrands/Create
        public IActionResult Create()
        {
            return this.View(new CarBrandEditModel());
        }

        // POST: CarBrands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( CarBrandEditModel model)
        {
            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.PathBrand.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            if (!CarBrandsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.PathBrand), "This file type is prohibited");
            }


            if (this.ModelState.IsValid)
            {
                var carBrand = new CarBrand
                {
                    Name = model.Name,
                    Description = model.Description                    

                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments/brands", carBrand.Id.ToString("N") + fileExt);
                carBrand.PathBrand = $"/attachments/brands/{carBrand.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.PathBrand.CopyToAsync(fileStream);
                }


                carBrand.Id = Guid.NewGuid();
                this._context.Add(carBrand);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Index");
            }
            return this.View(model);
        }

        // GET: CarBrands/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carBrand = await this._context.CarBrands.SingleOrDefaultAsync(m => m.Id == id);
            if (carBrand == null)
            {
                return this.NotFound();
            }
            var model = new CarBrandEditModel
            {
                Name = carBrand.Name,
                Description = carBrand.Description
            };

            this.ViewBag.CarBrand = carBrand;
            return this.View(model);
        }

        // POST: CarBrands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, CarBrandEditModel model)
        {
            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.PathBrand.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            if (!CarBrandsController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.PathBrand), "This file type is prohibited");
            }

            if (id == null)
            {
                return this.NotFound();
            }
            var carBrand = await this._context.CarBrands.SingleOrDefaultAsync(m => m.Id == id);
            if (carBrand == null)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments", carBrand.Id.ToString("N") + fileExt);
                carBrand.PathBrand = $"/attachments/{carBrand.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.PathBrand.CopyToAsync(fileStream);
                }

                carBrand.Name = model.Name;
                carBrand.Description = model.Description;

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Index");
            }

            this.ViewBag.CarBrand = carBrand;
            return this.View(model);
        }

        // GET: CarBrands/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carBrand = await this._context.CarBrands
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carBrand == null)
            {
                return this.NotFound();
            }

            return this.View(carBrand);
        }

        // POST: CarBrands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var carBrand = await this._context.CarBrands.SingleOrDefaultAsync(m => m.Id == id);
            this._context.CarBrands.Remove(carBrand);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction("Index");
        }

        private bool CarBrandExists(Guid id)
        {
            return this._context.CarBrands.Any(e => e.Id == id);
        }
    }
}

Backend6/Controllers/CarGradesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Models.ViewModels;
//using Backend6.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;


namespace Backend6.Controllers
{
    public class CarGradesController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        //private readonly IUserPermissionsService userPermissions;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarGradesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/*, IUserPermissionsService userPermissions*/, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            this.userManager = userManager;
            //this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CarGrades
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this._context.CarGrades
                .Include(c => c.CarModel);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: CarGrades/Details/5
        public async Task<IActionResult> Details(Guid? carGradeId)
        {
            if (carGradeId == null)
            {
                return this.NotFound();
            }

            var carGrade = await this._context.CarGrades
                .Include(v => v.CarParts)                
                .SingleOrDefaultAsync(m => m.Id == carGradeId);
            if (carGrade == null)
            {
                return this.NotFound();
            }
            this.ViewBag.CarGradeId = carGradeId;
            return this.View(carGrade);
        }

        [Authorize]
        // GET: CarGrades/Create
        public async Task<IActionResult> Create(Guid? carModelId)
        {
            if (carModelId == null)
            {
                return this.NotFound();
            }
            var carModel = await this._context.CarModels
                .SingleOrDefaultAsync(m => m.Id == carModelId);
            if (carModel == null)
            {
                return this.NotFound();
            }

            var carModels = await this._context.CarModels
                .OrderBy(x => x.Name).ToListAsync();
            this.ViewData["CarModelId"] = new SelectList(carModels, "Id", "Name");
            this.ViewBag.CarModels = carModel;
            return this.View(new CarGradeEditModel());
        }

        // POST: CarGrades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? carModelId, CarGradeEditModel model)
        {
            if (carModelId == null)
            {
                this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.GradePath.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            if (!CarGradesController.AllowedExtensions.Contains(fileExt))
            {
                this.ModelState.AddModelError(nameof(model.GradePath), "This file type is prohibited");
            }

            var carModel = await this._context.CarModels
                .SingleOrDefaultAsync(m => m.Id == carModelId);

            if (carModel == null)
            {
                this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                var carGrade = new CarGrade
                {
                    CarModelId = carModel.Id,
                    Name = model.Name,
                    Description = model.Description
                };

                var attachmentPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments/grades", carGrade.Id.ToString("N") + fileExt);
                carGrade.GradePath = $"/attachments/grades/{carGrade.Id:N}{fileExt}";
                using (var fileStream = new FileStream(attachmentPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.GradePath.CopyToAsync(fileStream);
                }


                carGrade.Id = Guid.NewGuid();
                this._context.Add(carGrade);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarModels", new { carModelId = carModel.Id });
            }
            this.ViewData["CarModelId"] = new SelectList(_context.CarModels, "Id", "ModelPath");
            this.ViewBag.CarModels = carModel;
            return this.View(model);
        }

        // GET: CarGrades/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carGrade = await this._context.CarGrades
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carGrade == null)
            {
                return this.NotFound();
            }
            this.ViewData["CarModelId"] = new SelectList(this._context.CarModels, "Id", "ModelPath", carGrade.CarModelId);
            return this.View(carGrade);
        }

        // POST: CarGrades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, CarGradeEditModel model)
        {
            if (id == null)
            {
                return this.NotFound();
            }
            var carGrade = await this._context.CarGrades
                .SingleOrDefaultAsync(m => m.Id == id);

            if (carGrade == null)
            {
                return this.NotFound();
            }
            if (this.ModelState.IsValid)
            {
                carGrade.Name = model.Name;
                carGrade.Description = model.Description;

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Details", "CarModels", new { carModelId = carGrade.CarModelId });
            }
            ViewData["CarModelId"] = new SelectList(this._context.CarModels, "Id", "ModelPath", carGrade.CarModelId);
            return this.View(model);
        }

        // GET: CarGrades/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var carGrade = await this._context.CarGrades
                .Include(c => c.CarModel)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carGrade == null)
            {
                return this.NotFound();
            }

            this.ViewBag.CarModels = carGrade;
            return this.View(carGrade);
        }

        // POST: CarGrades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid carModelId)
        {
            if (carModelId == null)
            {
                return this.NotFound();
            }

            var carGrade = await this._context.CarGrades
                .Include(c=> c.CarModel)
                .SingleOrDefaultAsync(m => m.Id == carModelId);
            if (carGrade == null)
            {
                return this.NotFound();
            }
            this._context.CarGrades.Remove(carGrade);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction("Details", "CarModels", new { carModelId = carGrade.CarModel.Id });
        }

        private bool CarGradeExists(Guid id)
        {
            return this._context.CarGrades.Any(e => e.Id == id);
        }
    }
}

Backend6/Views/CarModels/Create.cshtml
@model Backend6.Models.ViewModels.CarModelEditModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>CarModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-carBrandId="@ViewBag.CarBrands.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="CarBrandId" class="control-label"></label>
                <select asp-for="CarBrandId" class ="form-control" asp-items="ViewBag.CarBrandId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="ModelPath" class="control-label">Фото модели</label>
                <input type="file" asp-for="ModelPath" class="form-control" />
                <span asp-validation-for="ModelPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название модели</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Года выпуска</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarModels/Delete.cshtml
@model Backend6.Models.CarModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModelPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarBrand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarBrand.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-carBrandId="@Model.Id">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="CarBrands" asp-action="Index">Back to List</a>
    </form>
</div>

Backend6/Views/CarModels/Details.cshtml
@model Backend6.Models.CarModel

@{
    ViewData["Title"] = "Выберите раздел автомобиля который вам нужен";
}

<h2>@ViewBag.Title</h2>
<h1>@Model.Name<small> @Model.Description</small></h1>
<p>
    <a asp-controller="CarBrands" asp-action="Details" asp-route-backId="" class="btn btn-default">Back</a>
</p>

<div class="row">
    @if (User.IsInRole(ApplicationRoles.Administrators))
    {
        <div class="col-xs-3 col-md-2">
            <p>Добавить раздел</p>
            <a asp-action="Create" asp-controller="CarGrades" asp-route-carModelId="@ViewBag.CarModelId" class="thumbnail new-image">
                <div>
                    + Upload
                </div>
            </a>
        </div>
    }
    @foreach (var item in Model.CarGrades)
    {
        <div class="col-xs-3 col-md-2">
            <p>@item.Name</p>
            <a  asp-action="Details" asp-controller="CarGrades" asp-route-carGradeId="@item.Id" class="thumbnail image">
                <img src="@item.GradePath" alt="Image" />
            </a>
            @if (User.IsInRole(ApplicationRoles.Administrators))
            {
                <a asp-action="Edit" asp-controller="CarGrades" asp-route-id="@item.Id">Edit</a> <text>|</text>
                <a asp-action="Delete" asp-controller="CarGrades" asp-route-id="@item.Id">Delete</a>
            }
        </div>
    }
</div>

Backend6/Views/CarModels/Edit.cshtml
@model Backend6.Models.CarModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>CarModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CarBrandId" class="control-label"></label>
                <select asp-for="CarBrandId" class="form-control" asp-items="ViewBag.CarBrandId"></select>
                <span asp-validation-for="CarBrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelPath" class="control-label"></label>
                <input asp-for="ModelPath" class="form-control" />
                <span asp-validation-for="ModelPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/CarModels/Index.cshtml
@model IEnumerable<Backend6.Models.CarModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Как с нами связаться?</h2>

<div>Никак)</div>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ModelPath)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                <th>
                    @Html.DisplayNameFor(model => model.CarBrand)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelPath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CarBrand.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@